<?php
define('MYSQL_SERVER', $_ENV['MYSQL_SERVER']);
define('MYSQL_PORT', $_ENV['MYSQL_PORT']);
define('MYSQL_USER', $_ENV['MYSQL_USER']);
define('MYSQL_DATABASE', $_ENV['MYSQL_DATABASE']);
define('MYSQL_PASSWORD', $_ENV['MYSQL_PASSWORD']);
